// Constants for CityBuilder Classic (port from xShunter's version.nut)

CONGESTION_DONT_CARE <- 1
CONGESTION_GROW_HALFED <- 2
CONGESTION_GROW_QUARTERED <- 3
CONGESTION_GROW_STOP <- 4

CACHE_CONGESTION_DIFFICULTY_FACTOR <- 1
CACHE_PERIODICGROWTH_RATE <- 2
CACHE_CONGESTION_GROWTH_FACTOR <-3
CACHE_CARGOGOAL_DIFFICULTY_FACTOR <- 4
