SCRIPT_VERSION <- 2;
DIV_VERSION <- 7;
NOVACB_VERSION <- 9;
CARGOBEE_VERSION <- 1;

PROGRAM_VERSION <- 5873;
PROGRAM_DATE <- "2015-03-01";
PROGRAM_NAME <- "BusyBee RC2M";

SELF_VERSION <- 117;

CONGESTION_DONT_CARE <- 1
CONGESTION_GROW_HALFED <- 2
CONGESTION_GROW_QUARTERED <- 3
CONGESTION_GROW_STOP <- 4

CACHE_CONGESTION_DIFFICULTY_FACTOR <- 1
CACHE_PERIODICGROWTH_RATE <- 2
CACHE_CONGESTION_GROWTH_FACTOR <-3
CACHE_CARGOGOAL_DIFFICULTY_FACTOR <- 4
